<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { adminApi } from '@/api/admin'
import type { SystemMetrics } from '@/types/api'

const window = ref<'CURRENT' | 'TODAY'>('CURRENT'); const metrics = ref<SystemMetrics | null>(null); const loading = ref(false); const staleAt = ref<string | null>(null); const unavailable = ref(false)
const time = (value?: string | null) => value ? new Date(value).toLocaleString() : '—'
const cards = computed(() => { const m = metrics.value; if (!m) return []; return [{ label: '连接数', value: m.webSocketConnectionCount }, { label: '待审核数', value: m.pendingReviewCount }, { label: '今日审核超时', value: m.reviewTimeoutCountToday }, { label: '今日消息量', value: m.messageCountToday }, { label: '平均审核耗时', value: `${m.averageReviewLatencyMsToday} ms` }, { label: '今日推送失败', value: m.pushFailureCountToday }, { label: 'HTTP 错误率', value: `${(m.httpErrorRate * 100).toFixed(2)}%` }, { label: '数据库连接池', value: `${m.databasePool.active} / ${m.databasePool.idle} / ${m.databasePool.max}`, caption: '活跃 / 空闲 / 上限' }] })
async function load(): Promise<void> { loading.value = true; unavailable.value = false; try { metrics.value = await adminApi.metrics(window.value); staleAt.value = null } catch { unavailable.value = true; staleAt.value ??= new Date().toISOString() } finally { loading.value = false } }
onMounted(load)
</script>
<template><section class="admin-page"><div class="page-heading"><div><h2>运行状态</h2><p>系统聚合指标不包含用户内容。观察时间：{{time(metrics?.observedAt)}}</p></div><el-space><el-radio-group v-model="window" @change="load"><el-radio-button value="CURRENT">当前</el-radio-button><el-radio-button value="TODAY">今日</el-radio-button></el-radio-group><el-button :loading="loading" @click="load">刷新</el-button></el-space></div><el-alert v-if="unavailable" title="指标暂不可用" :description="metrics ? `保留最近一次成功数据；数据可能已过期（${time(staleAt)}）。` : '请稍后刷新。'" type="warning" :closable="false" class="alert"/><div v-if="cards.length" class="metrics-grid"><el-card v-for="card in cards" :key="card.label" shadow="never"><div class="metric-label">{{card.label}}</div><div class="metric-value">{{card.value}}</div><div class="metric-caption">{{card.caption ?? ' '}}</div></el-card></div><el-empty v-else-if="!loading" description="指标暂不可用"/></section></template><style scoped>.page-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-heading h2{margin:0 0 6px}.page-heading p{margin:0;color:var(--el-text-color-secondary)}.alert{margin-bottom:16px}.metrics-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.metric-label,.metric-caption{color:var(--el-text-color-secondary);font-size:13px}.metric-value{font-size:26px;font-weight:700;margin:12px 0}.metric-caption{min-height:18px}@media (max-width:1100px){.metrics-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
