<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminApi } from '@/api/admin'
import type { AdminRoom, ReviewMessage } from '@/types/api'

type Message = ReviewMessage

const rows = ref<ReviewMessage[]>([]); const rooms = ref<AdminRoom[]>([]); const loading = ref(false); const selected = ref<ReviewMessage[]>([]); const detail = ref<ReviewMessage | null>(null) as any; const result = ref<Array<{ messageId: string; reviewResult: string; messageStatus?: string; errorCode?: string }>>([])
const filter = reactive({ roomId: '', senderId: '', messageStatus: 'PENDING_REVIEW', createdFrom: '', createdTo: '' })
const canBatch = computed(() => selected.value.length >= 1 && selected.value.length <= 100)
const time = (value?: string) => value ? new Date(value).toLocaleString() : '—'; const roomName = (id: string) => rooms.value.find((room) => room.id === id)?.name ?? id
async function load(): Promise<void> { loading.value = true; try { rows.value = (await adminApi.reviews({ ...filter, page: 1, size: 100 })).items; selected.value = [] } finally { loading.value = false } }
async function review(row: ReviewMessage, action: 'approve' | 'reject'): Promise<void> { try { const next = await adminApi.review(row.id, action); rows.value = rows.value.map((item) => item.id === row.id ? next : item); ElMessage.success(action === 'approve' ? '审核已通过；消息可能仍在等待前序消息发布。' : '已拒绝该消息') } catch (error) { if ((error as { apiError?: { code?: string } }).apiError?.code === 'REVIEW_ALREADY_PROCESSED') { ElMessage.warning('此消息已被处理，已刷新列表。'); await load() } else throw error } }
async function batch(action: 'APPROVE' | 'REJECT'): Promise<void> { await ElMessageBox.confirm(`确定${action === 'APPROVE' ? '批准' : '拒绝'}选中的 ${selected.value.length} 条消息吗？`, '批量审核', { type: 'warning' }); const response = await adminApi.batchReview(selected.value.map((item) => item.id), action); result.value = response.results; await load() }
onMounted(async () => { rooms.value = (await adminApi.rooms({ page: 1, size: 100 })).items; await load() })
</script>
<template><section class="admin-page"><div class="page-heading"><div><h2>内容审核</h2><p>批准并不等于已发布；消息会按房间序号等待前序消息完成发布或跳过。</p></div><el-space><el-button :disabled="!canBatch" @click="batch('REJECT')">拒绝所选</el-button><el-button :disabled="!canBatch" type="primary" @click="batch('APPROVE')">批准所选</el-button></el-space></div>
<el-card shadow="never"><el-form :inline="true" class="filter-bar"><el-form-item label="房间"><el-select v-model="filter.roomId" clearable filterable><el-option v-for="room in rooms" :key="room.id" :label="room.name" :value="room.id"/></el-select></el-form-item><el-form-item label="发送者 ID"><el-input v-model="filter.senderId"/></el-form-item><el-form-item label="状态"><el-select v-model="filter.messageStatus"><el-option v-for="status in ['PENDING_REVIEW','APPROVED','REJECTED','TIMEOUT']" :key="status" :label="status" :value="status"/></el-select></el-form-item><el-form-item label="提交时间"><el-date-picker v-model="filter.createdFrom" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss[Z]" placeholder="开始"/><span class="date-divider">至</span><el-date-picker v-model="filter.createdTo" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss[Z]" placeholder="结束"/></el-form-item><el-button @click="load">查询</el-button></el-form></el-card>
<el-card shadow="never" class="table-card"><el-table :data="rows" v-loading="loading" @selection-change="selected = $event"><el-table-column type="selection" width="48" :selectable="(row: Message) => row.status === 'PENDING_REVIEW'"/><el-table-column label="内容" min-width="260" show-overflow-tooltip><template #default="{row}"><el-button link @click="detail=row">{{ row.content }}</el-button></template></el-table-column><el-table-column label="发送者" min-width="180"><template #default="{row}">{{row.senderId}}</template></el-table-column><el-table-column label="房间" min-width="130"><template #default="{row}">{{roomName(row.roomId)}}</template></el-table-column><el-table-column label="提交时间" width="170"><template #default="{row}">{{time(row.createdAt)}}</template></el-table-column><el-table-column label="截止时间" width="170"><template #default="{row}">{{time(row.reviewDeadlineAt)}}</template></el-table-column><el-table-column label="状态" width="130"><template #default="{row}"><el-tag :type="row.status === 'PENDING_REVIEW' ? 'warning' : row.status === 'REJECTED' ? 'danger' : 'info'">{{row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="145"><template #default="{row}"><el-space v-if="row.status === 'PENDING_REVIEW'"><el-button type="primary" link @click="review(row,'approve')">批准</el-button><el-button type="danger" link @click="review(row,'reject')">拒绝</el-button></el-space><span v-else>—</span></template></el-table-column></el-table></el-card>
<el-card v-if="result.length" shadow="never" class="result-card"><template #header>批量审核结果（逐条）</template><el-table :data="result"><el-table-column prop="messageId" label="消息 ID" min-width="280"/><el-table-column prop="reviewResult" label="处理结果" width="160"/><el-table-column prop="messageStatus" label="当前状态" width="150"/><el-table-column prop="errorCode" label="原因" min-width="180"/></el-table></el-card>
<el-drawer v-model="detail" :title="detail ? '审核详情' : ''" size="480px"><template v-if="detail"><p><strong>房间序号：</strong>{{detail.roomSeq ?? '—'}}</p><p><strong>内容：</strong>{{detail.content}}</p><p><strong>状态：</strong>{{detail.status}}</p><el-alert v-if="detail.status === 'APPROVED'" title="审核已通过；该消息会在前序消息完成发布或跳过后自动发布。" type="info" :closable="false" /></template></el-drawer>
</section></template><style scoped>.page-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.page-heading h2{margin:0 0 6px}.page-heading p{margin:0;color:var(--el-text-color-secondary)}.filter-bar{margin-bottom:-18px}.table-card,.result-card{margin-top:16px}.date-divider{margin:0 8px}</style>
